default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: konstantin
  password: 
  host: localhost

development:
  <<: *default
  database: users_list_dev

test:
  <<: *default
  database: users_list_test

production:
  <<: *default
  database: users_list_production
